In [1]:
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import LinearSVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import GradientBoostingRegressor

In [2]:
import pandas as pd
import numpy as np
from sklearn import model_selection
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.model_selection import train_test_split

In [3]:
model1 = RandomForestRegressor()
model2 = XGBRegressor()
model3 = DecisionTreeRegressor()
model4 = GradientBoostingRegressor()

In [4]:
dataset = pd.read_csv("New SR Data.csv")
data = dataset.values
X, y = data[:, :-1], data[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=981)

In [5]:
print("model 1")
model1.fit(X_train,y_train)
preds = model1.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, preds))
R2= (r2_score(y_test, preds))
print("r2_score: %f"% (R2))
print("RMSE: %f" % (rmse))
mse = (mean_squared_error(y_test, preds))
print("MSE: %f" % (mse))
#np.savetxt("model1_353_1M_beha_predictions_sheet1_score1.csv", preds, delimiter=",")
#np.savetxt("model1_353_1M_beha_groundtruth_sheet1_score1.csv", y_test, delimiter=",")

print("model 2")
model2.fit(X_train,y_train)
preds = model2.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, preds))
R2= (r2_score(y_test, preds))
print("r2_score: %f"% (R2))
print("RMSE: %f" % (rmse))
mse = (mean_squared_error(y_test, preds))
print("MSE: %f" % (mse))
#np.savetxt("model2_353_1M_beha_predictions_sheet1_score1.csv", preds, delimiter=",")
#np.savetxt("model2_353_1M_beha_groundtruth_sheet1_score1.csv", y_test, delimiter=",")

print("model 3")
model3.fit(X_train,y_train)
preds = model3.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, preds))
R2= (r2_score(y_test, preds))
print("r2_score: %f"% (R2))
print("RMSE: %f" % (rmse))
mse = (mean_squared_error(y_test, preds))
print("MSE: %f" % (mse))
#np.savetxt("model3_353_1M_beha_predictions_sheet1_score1.csv", preds, delimiter=",")
#np.savetxt("model3_353_1M_beha_groundtruth_sheet1_score1.csv", y_test, delimiter=",")

print("model 4")
model4.fit(X_train,y_train)
preds = model4.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, preds))
R2= (r2_score(y_test, preds))
print("r2_score: %f"% (R2))
print("RMSE: %f" % (rmse))
mse = (mean_squared_error(y_test, preds))
print("MSE: %f" % (mse))
#np.savetxt("model4_353_1M_beha_predictions_sheet1_score1.csv", preds, delimiter=",")
#np.savetxt("model4_353_1M_beha_groundtruth_sheet1_score1.csv", y_test, delimiter=",")



model 1
r2_score: 0.921877
RMSE: 0.116488
MSE: 0.013570
model 2
r2_score: 0.962524
RMSE: 0.080680
MSE: 0.006509
model 3
r2_score: 0.743373
RMSE: 0.211128
MSE: 0.044575
model 4
r2_score: 0.905861
RMSE: 0.127873
MSE: 0.016351


In [6]:
dataset = pd.read_csv("New SR Data.csv")
data = dataset.values
X, y = data[:, :-1], data[:, -1]

In [7]:
preds = model1.predict(X)

In [8]:
preds

array([2.70362442, 2.37084346, 1.65196843, 2.26502811, 2.01578122,
       2.42799419, 1.92163309, 1.82043008, 1.9060792 , 2.02797527,
       2.01578122, 1.98577722, 1.87060805, 2.01578122, 2.93019747,
       1.89744539, 2.07931795, 1.83971102, 2.08752565, 1.66741695,
       2.0932712 , 2.11783387, 1.88061524, 2.73023966, 2.56364775,
       2.71337077, 2.59402312])

In [9]:
R2= (r2_score(y, preds))
print("r2_score: %f"% (R2))
rmse = np.sqrt(mean_squared_error(y, preds))
print("RMSE: %f" % (rmse))
mse = (mean_squared_error(y, preds))
print("MSE: %f" % (mse))
np.savetxt("model1_353_1M_beha_predictions_sheet1_score1.csv", preds, delimiter=",")

r2_score: 0.934814
RMSE: 0.104279
MSE: 0.010874


In [10]:
preds = model2.predict(X)

In [11]:
preds

array([2.730981 , 2.444354 , 1.5236632, 2.3084235, 2.0267618, 2.5368512,
       1.8839822, 1.5733061, 1.8145825, 1.8846002, 2.0267618, 1.9176878,
       1.9638433, 2.0267618, 3.0693817, 1.8229431, 2.1012938, 1.6654482,
       2.2678175, 1.5775237, 2.2344737, 2.248895 , 1.960694 , 2.7436275,
       2.5619495, 2.7310069, 2.5816965], dtype=float32)

In [12]:
R2= (r2_score(y, preds))
print("r2_score: %f"% (R2))
rmse = np.sqrt(mean_squared_error(y, preds))
print("RMSE: %f" % (rmse))
mse = (mean_squared_error(y, preds))
print("MSE: %f" % (mse))
np.savetxt("model2_353_1M_beha_predictions_sheet1_score1.csv", preds, delimiter=",")

r2_score: 0.986861
RMSE: 0.046816
MSE: 0.002192


In [13]:
preds = model3.predict(X)

In [14]:
preds

array([2.743648 , 2.445111 , 1.522642 , 2.307722 , 2.0262295, 2.537048 ,
       1.884192 , 1.577391 , 1.577391 , 1.884192 , 2.0262295, 1.917248 ,
       1.963733 , 2.0262295, 3.071109 , 1.522642 , 2.101122 , 1.664163 ,
       2.269501 , 1.577391 , 2.537048 , 2.269501 , 1.961667 , 2.743648 ,
       2.743648 , 2.743648 , 2.581467 ])

In [15]:
R2= (r2_score(y, preds))
print("r2_score: %f"% (R2))
rmse = np.sqrt(mean_squared_error(y, preds))
print("RMSE: %f" % (rmse))
mse = (mean_squared_error(y, preds))
print("MSE: %f" % (mse))
np.savetxt("model3_353_1M_beha_predictions_sheet1_score1.csv", preds, delimiter=",")

r2_score: 0.910801
RMSE: 0.121983
MSE: 0.014880


In [16]:
preds = model4.predict(X)

In [17]:
preds

array([2.6557305 , 2.4446829 , 1.52481964, 2.30773798, 2.02670824,
       2.53760092, 1.88458646, 1.7500095 , 1.82751812, 1.88324336,
       2.02670824, 1.91588272, 1.96290664, 2.02670824, 3.07091015,
       1.81700374, 2.10780359, 1.66555409, 2.26369839, 1.58261041,
       2.37175489, 2.24247079, 1.95468882, 2.74292096, 2.63204128,
       2.68073358, 2.58135149])

In [18]:
R2= (r2_score(y, preds))
print("r2_score: %f"% (R2))
rmse = np.sqrt(mean_squared_error(y, preds))
print("RMSE: %f" % (rmse))
mse = (mean_squared_error(y, preds))
print("MSE: %f" % (mse))
np.savetxt("model4_353_1M_beha_predictions_sheet1_score1.csv", preds, delimiter=",")

r2_score: 0.967160
RMSE: 0.074015
MSE: 0.005478
