In [26]:
from sklearn.neural_network import MLPRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor
# from sklearn.ensemble import StackingRegressor
# from sklearn.ensemble import VotingRegressor
# from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import LinearSVR
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor

import pandas as pd
import numpy as np
from sklearn import model_selection
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.model_selection import train_test_split

model1 = RandomForestRegressor()
model2 = SVR()

dataset = pd.read_csv( "Surface Roughness Al GnP NF.csv")
data = dataset.values
X, y = data[:, :-1], data[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

print("model 1")
model1.fit(X_train,y_train)
preds = model1.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, preds))
R2= (r2_score(y_test, preds))
print("r2_score: %f"% (R2))
print("RMSE: %f" % (rmse))
mse = (mean_squared_error(y_test, preds))
print("MSE: %f" % (mse))
np.savetxt("model1_353_1M_beha_predictions_sheet1_score1.csv", preds, delimiter=",")
np.savetxt("model1_353_1M_beha_groundtruth_sheet1_score1.csv", y_test, delimiter=",")

print("model 2")
model2.fit(X_train,y_train)
preds = model2.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, preds))
R2= (r2_score(y_test, preds))
print("r2_score: %f"% (R2))
print("RMSE: %f" % (rmse))
mse = (mean_squared_error(y_test, preds))
print("MSE: %f" % (mse))
np.savetxt("model2_353_1M_beha_predictions_sheet1_score1.csv", preds, delimiter=",")
np.savetxt("model2_353_1M_beha_groundtruth_sheet1_score1.csv", y_test, delimiter=",")

model 1
r2_score: 0.704825
RMSE: 0.217735
MSE: 0.047409
model 2
r2_score: 0.121929
RMSE: 0.375538
MSE: 0.141029


In [18]:
dataset = pd.read_csv("Surface Roughness Al GnP NF.csv")
data = dataset.values
X, y = data[:, :-1], data[:, -1]

In [19]:
preds = model1.predict(X)

In [20]:
preds

array([2.10493   , 1.74589667, 1.43385833, 1.776321  , 1.57411667,
       1.76103   , 1.48405167, 1.44598167, 1.39012767, 1.55515   ,
       1.57411667, 1.63940333, 1.31479133, 1.57411667, 2.11149   ,
       1.60251933, 1.651938  , 1.49006933, 1.65311   , 1.417025  ,
       1.62084   , 1.648978  , 1.43394633, 2.11037   , 2.064915  ,
       2.14208   , 1.945935  ])

In [21]:
R2= (r2_score(y, preds))
print("r2_score: %f"% (R2))
rmse = np.sqrt(mean_squared_error(y, preds))
print("RMSE: %f" % (rmse))
mse = (mean_squared_error(y, preds))
print("MSE: %f" % (mse))
np.savetxt("model1_353_1M_beha_predictions_sheet1_score1.csv", preds, delimiter=",")

r2_score: 0.827200
RMSE: 0.129588
MSE: 0.016793


In [6]:
preds = model2.predict(X)

In [7]:
preds

array([1.62252793, 1.68704303, 1.55772056, 1.68699999, 1.62250851,
       1.68729152, 1.55799998, 1.55798753, 1.62252332, 1.68702046,
       1.62250851, 1.55826382, 1.62221296, 1.62250851, 1.68702434,
       1.55798117, 1.62280406, 1.62248909, 1.62281888, 1.62219354,
       1.68674827, 1.62283829, 1.62217873, 1.6224937 , 1.62219814,
       1.62282349, 1.55799184])

In [22]:
dataset = pd.read_csv("Surface Roughness Al GnP NF.csv")
data = dataset.values
X, y = data[:, :-1], data[:, -1]

In [23]:
preds = model2.predict(X)

In [24]:
preds

array([1.62252793, 1.68704303, 1.55772056, 1.68699999, 1.62250851,
       1.68729152, 1.55799998, 1.55798753, 1.62252332, 1.68702046,
       1.62250851, 1.55826382, 1.62221296, 1.62250851, 1.68702434,
       1.55798117, 1.62280406, 1.62248909, 1.62281888, 1.62219354,
       1.68674827, 1.62283829, 1.62217873, 1.6224937 , 1.62219814,
       1.62282349, 1.55799184])

In [25]:
R2= (r2_score(y, preds))
print("r2_score: %f"% (R2))
rmse = np.sqrt(mean_squared_error(y, preds))
print("RMSE: %f" % (rmse))
mse = (mean_squared_error(y, preds))
print("MSE: %f" % (mse))
np.savetxt("model2_353_1M_beha_predictions_sheet1_score1.csv", preds, delimiter=",")

r2_score: 0.070257
RMSE: 0.300589
MSE: 0.090354
