In [13]:
from sklearn.neural_network import MLPRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor
# from sklearn.ensemble import StackingRegressor
# from sklearn.ensemble import VotingRegressor
# from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import LinearSVR
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor

import pandas as pd
import numpy as np
from sklearn import model_selection
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.model_selection import train_test_split

model1 = RandomForestRegressor()
model2 = SVR()

dataset = pd.read_csv("Surface Roughness Al NF.csv")
data = dataset.values
X, y = data[:, :-1], data[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

print("model 1")
model1.fit(X_train,y_train)
preds = model1.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, preds))
R2= (r2_score(y_test, preds))
print("r2_score: %f"% (R2))
print("RMSE: %f" % (rmse))
mse = (mean_squared_error(y_test, preds))
print("MSE: %f" % (mse))
np.savetxt("model1_353_1M_beha_predictions_sheet1_score1.csv", preds, delimiter=",")
np.savetxt("model1_353_1M_beha_groundtruth_sheet1_score1.csv", y_test, delimiter=",")

print("model 2")
model2.fit(X_train,y_train)
preds = model2.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, preds))
R2= (r2_score(y_test, preds))
print("r2_score: %f"% (R2))
print("RMSE: %f" % (rmse))
mse = (mean_squared_error(y_test, preds))
print("MSE: %f" % (mse))
np.savetxt("model2_353_1M_beha_predictions_sheet1_score1.csv", preds, delimiter=",")
np.savetxt("model2_353_1M_beha_groundtruth_sheet1_score1.csv", y_test, delimiter=",")

model 1
r2_score: 0.794395
RMSE: 0.233106
MSE: 0.054338
model 2
r2_score: 0.147181
RMSE: 0.474750
MSE: 0.225388


In [3]:
dataset = pd.read_csv("Surface Roughness Al NF.csv")
data = dataset.values
X, y = data[:, :-1], data[:, -1]

In [4]:
preds = model1.predict(X)

In [5]:
preds

array([2.6334475, 2.24637  , 1.8999685, 2.19799  , 1.9632135, 2.177455 ,
       1.8644355, 1.652645 , 1.7320925, 1.89548  , 1.9632135, 2.009475 ,
       1.9221055, 1.9632135, 2.6435   , 1.8876905, 2.061475 , 1.762345 ,
       2.05337  , 1.75576  , 2.13404  , 2.070805 , 1.9278605, 2.6336975,
       2.63471  , 2.66373  , 2.55964  ])

In [6]:
R2= (r2_score(y, preds))
print("r2_score: %f"% (R2))
rmse = np.sqrt(mean_squared_error(y, preds))
print("RMSE: %f" % (rmse))
mse = (mean_squared_error(y, preds))
print("MSE: %f" % (mse))
#np.savetxt("model2_353_1M_beha_predictions_sheet1_score1.csv", preds, delimiter=",")

r2_score: 0.862775
RMSE: 0.146475
MSE: 0.021455


In [7]:
R2= (r2_score(y, preds))
print("r2_score: %f"% (R2))
rmse = np.sqrt(mean_squared_error(y, preds))
print("RMSE: %f" % (rmse))
mse = (mean_squared_error(y, preds))
print("MSE: %f" % (mse))
#np.savetxt("model1_353_1M_beha_predictions_sheet1_score1.csv", preds, delimiter=",")

r2_score: 0.862775
RMSE: 0.146475
MSE: 0.021455


In [8]:
dataset = pd.read_csv("Surface Roughness Al NF.csv")
data = dataset.values
X, y = data[:, :-1], data[:, -1]

In [9]:
preds = model1.predict(X)

In [10]:
preds

array([2.6334475, 2.24637  , 1.8999685, 2.19799  , 1.9632135, 2.177455 ,
       1.8644355, 1.652645 , 1.7320925, 1.89548  , 1.9632135, 2.009475 ,
       1.9221055, 1.9632135, 2.6435   , 1.8876905, 2.061475 , 1.762345 ,
       2.05337  , 1.75576  , 2.13404  , 2.070805 , 1.9278605, 2.6336975,
       2.63471  , 2.66373  , 2.55964  ])

In [11]:
preds = model2.predict(X)

In [12]:
preds

array([2.02852328, 2.13403461, 1.9227258 , 2.13399999, 2.02850851,
       2.13428629, 1.92299999, 1.92299117, 2.02851867, 2.13401682,
       2.02850851, 1.92326905, 2.0282083 , 2.02850851, 2.1340207 ,
       1.92298958, 2.02880872, 2.02849375, 2.02881888, 2.02819354,
       2.13374303, 2.02883364, 2.02818338, 2.02849835, 2.02819814,
       2.02882349, 1.92299548])